
version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1
    ports:
      - "9042:9042"
    networks:
      cassandra_network:
        ipv4_address: 192.168.0.2

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1
    depends_on:
      - cassandra1
    networks:
      cassandra_network:
        ipv4_address: 192.168.0.3

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1
    depends_on:
      - cassandra1
    networks:
      cassandra_network:
        ipv4_address: 192.168.0.4

networks:
  cassandra_network:
    driver: bridge
